### PR TITLE
Tweak to install libraries where they can be used

### PR DESCRIPTION
**Pull request by omerida**
Ran into this trying to use the superfish module.

### CODE REVIEW

**Comment by pjcdawkins** [comment]
I guess it is normal not to use the "contrib" subdirectory pattern for libraries? (I've seen it this way before, modules/contrib, themes/contrib and libraries/).

If so then this LGTM.

**Comment by pjcdawkins** [comment]
... oh but the composer.lock hash is probably out of date, it needs a `composer update --lock` at least

**Comment by omerida** [comment]
I'm not sure if its widely practiced but the discussions here recommen a /libraries folder for js and other assets shared across modules. https://www.drupal.org/project/documentation/issues/2605130

**Comment by pjcdawkins** [comment]
I updated the hash with `composer update --lock` before merging.

Thanks @omerida!

**Pull request merged**
